apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go
  labels:
    app: example-go
spec:
  selector:
    matchLabels:
      app: example-go
  template:
    metadata:
      labels:
        app: example-go
    spec:
      containers:
      - name: example-go
        image: tilt-my-dev
        ports:
        - containerPort: 3000

# apiVersion: v1
# kind: Service
# metadata:
#   name: example-go
#   namespace: default
# spec:
#   selector:
#     app: example-go
#   ports:
#     - port: 80
#       targetPort: 3000
#   type: LoadBalancer